name: Incline
title: "Incline: web and app development, process automation and optimization"
description: Software engineering and business consulting - we help businesses launch, grow, and profit.
google)analytics: UA-97706767-1
sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap/scss
  style: compressed
exclude: ['assets/source-images']
nav:
# - url: /javascript/
#   name: JavaScript Experts
# - url: /clients/
#   name: Clients
