theme: jekyll-theme-cayman
name: Incline
title: "Incline: web and app development, process automation and optimization"
description: Software engineering and business consulting - we help businesses launch, grow, and profit.
google)analytics: UA-97706767-1
